spring:
  application:
    name: ${APP_NAME:site-word-stats}
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/test
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}
logging:
  level:
    root:
      error
  file:
    name: log/log.txt
